### ISSUE TITLE
New PHP Library

### ISSUE THREAD

**Issue by rbarden** [traindown/spec#2]
Hey there! 

As  I previously mentioned, I've been working on a PHP library for traindown. You can check it out at https://github.com/rbarden/traindown-php. I can transfer the repo to the traindown organization if you want it, or keep it under my account. It's still a work in progress, obviously, it doesn't have tests etc. But I think that if someone uses it, it'll be easier to see what needs to change based on usage.

**Comment by scottt2** [comment]
Thanks again, @rbarden ! Closing as we have now transferred this guy into the org.
